// utils/flags.ts
export function iocToIso2(ioc?: string | null): string | null {
  const m: Record<string, string> = {
    AFG: "AF",
    ALB: "AL",
    ALG: "DZ",
    AND: "AD",
    ANG: "AO",
    ANT: "AG",
    ARG: "AR",
    ARM: "AM",
    ARU: "AW",
    AUS: "AU",
    AUT: "AT",
    AZE: "AZ",
    BAH: "BS",
    BAN: "BD",
    BAR: "BB",
    BEL: "BE",
    BER: "BM",
    BOL: "BO",
    BOT: "BW",
    BRA: "BR",
    BRN: "BH",
    BRU: "BN",
    BUL: "BG",
    BUR: "BF",
    BDI: "BI",
    CAM: "KH",
    CMR: "CM",
    CAN: "CA",
    CAY: "KY",
    CGO: "CG",
    CHA: "TD",
    CHI: "CL",
    CHN: "CN",
    CIV: "CI",
    COD: "CD",
    CRO: "HR",
    CUB: "CU",
    CYP: "CY",
    CZE: "CZ",
    DEN: "DK",
    DJI: "DJ",
    DMA: "DM",
    DOM: "DO",
    ECU: "EC",
    EGY: "EG",
    ESA: "SV",
    ESP: "ES",
    EST: "EE",
    ETH: "ET",
    FIJ: "FJ",
    FIN: "FI",
    FRA: "FR",
    FSM: "FM",
    GAB: "GA",
    GAM: "GM",
    GBR: "GB",
    GEO: "GE",
    GER: "DE",
    GHA: "GH",
    GRE: "GR",
    GUA: "GT",
    GUI: "GN",
    GUY: "GY",
    HON: "HN",
    HKG: "HK",
    HUN: "HU",
    INA: "ID",
    IND: "IN",
    IRI: "IR",
    IRL: "IE",
    ISR: "IL",
    ITA: "IT",
    IVB: "VG",
    JAM: "JM",
    JPN: "JP",
    KAZ: "KZ",
    KEN: "KE",
    KGZ: "KG",
    KOR: "KR",
    KSA: "SA",
    KUW: "KW",
    LAO: "LA",
    LAT: "LV",
    LIB: "LB",
    LIE: "LI",
    LTU: "LT",
    LUX: "LU",
    MAD: "MG",
    MAS: "MY",
    MDA: "MD",
    MDV: "MV",
    MEX: "MX",
    MGL: "MN",
    MKD: "MK",
    MLI: "ML",
    MLT: "MT",
    MOZ: "MZ",
    MRI: "MU",
    NAM: "NA",
    NED: "NL",
    NGR: "NG",
    NIG: "NE",
    NOR: "NO",
    NZL: "NZ",
    OMA: "OM",
    PAK: "PK",
    PAN: "PA",
    PAR: "PY",
    PER: "PE",
    PHI: "PH",
    PLE: "PS",
    PNG: "PG",
    POL: "PL",
    POR: "PT",
    PUR: "PR",
    QAT: "QA",
    ROU: "RO",
    RSA: "ZA",
    RUS: "RU",
    SAM: "WS",
    SUI: "CH",
    SWE: "SE",
    SYR: "SY",
    TPE: "TW",
    THA: "TH",
    TUN: "TN",
    TUR: "TR",
    TTO: "TT",
    UAE: "AE",
    UGA: "UG",
    UKR: "UA",
    URU: "UY",
    USA: "US",
    UZB: "UZ",
    VEN: "VE",
    VIE: "VN",
    ZAM: "ZM",
    ZIM: "ZW",
    // puoi aggiungere altri codici IOC speciali / territori se servono
  };

  if (!ioc) return null;
  const iso = m[ioc.toUpperCase()];
  return iso ?? null;
}


export function flagEmoji(iso2?: string | null) {
  if (!iso2) return null;
  const up = iso2.toUpperCase();
  if (!/^[A-Z]{2}$/.test(up)) return null;
  return String.fromCodePoint(...Array.from(up).map((c) => 0x1f1e6 + (c.charCodeAt(0) - 65)));
}